[package]
name = "rustlearn"
version = "0.1.0"
authors = ["maciejkula <maciej.kula@gmail.com>"]

[dependencies]

bincode = "*"
csv = "0.14"
rand = "0.3"
rustc-serialize = "0.3"
time = "0.1"


[features]
all_tests = []
bench = []
